Repository oatpp/oatpp, pull requests merged in 2020-07, with the labels that each got.

#270 Proposal for #261: Fine grained configurable Loglevel
  src/oatpp/core/base/Environment.cpp
  src/oatpp/core/base/Environment.hpp
  test/CMakeLists.txt
  test/oatpp/AllTestsMain.cpp
  test/oatpp/core/base/LoggerTest.cpp
  test/oatpp/core/base/LoggerTest.hpp
Labels: API Proposal, enhancement

#274 fix cannot serialize 'false' value
  src/oatpp/web/client/ApiClient.hpp
Labels: changes requested

#278 oatpp::data::stream::BufferOutputStream. Optimize growth.
  src/CMakeLists.txt
  src/oatpp/core/data/stream/BufferStream.cpp
  src/oatpp/core/data/stream/BufferStream.hpp
  src/oatpp/core/utils/Binary.cpp
  src/oatpp/core/utils/Binary.hpp
  src/oatpp/web/protocol/http/encoding/Chunked.cpp
  src/oatpp/web/protocol/http/outgoing/Request.cpp
  src/oatpp/web/server/HttpProcessor.cpp
  src/oatpp/web/server/HttpProcessor.hpp
  test/oatpp/AllTestsMain.cpp
  test/oatpp/core/data/stream/BufferStreamTest.cpp
Labels: enhancement
